name: Create PR from Google Sheets
on: 
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook
jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GS_API_KEY: ${{ secrets.GS_API_KEY }}
    steps:
      - name: Get updates from google sheets
        uses: actions/checkout@v2
      - run: |
          cd ./scripts
          python get-json.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
        with:
          title: Updates from google sheet   
          delete-branch: true
        
